### ISSUE TITLE
OSError - issue creating mol2 file

### ISSUE THREAD

**Issue by annaliesemeyer** [alexandrova-lab-ucla/phd3#2]
Hi,

I am running into a persistent issue with setupphd.py and setupdmd.py not creating the mol2 file for my pdb input. This occurs regardless of in which directory I call it and has occurred with several different protein inputs. Any help would be appreciated! Please see error messages below. Thank you.
```
(phd3-3.8) [anmeyer@pn040 jsoninputs]$ ls
4rdt_loops.pdb  phdinput.json
(phd3-3.8) [anmeyer@pn040 jsoninputs]$ setupphd.py
	Could not create 4rdt_loops.pdb mol2 file!
	OSError encountered, likely an issue with moving files around
Traceback (most recent call last):
  File "/vortexfs1/home/anmeyer/.local/lib/python3.8/site-packages/phd3/bin/setupphd.py", line 24, in main
    sdj = setupPHDjob()
  File "/vortexfs1/home/anmeyer/.local/lib/python3.8/site-packages/phd3/setupjob.py", line 1338, in __init__
    sdj.full_setup()
  File "/vortexfs1/home/anmeyer/.local/lib/python3.8/site-packages/phd3/setupjob.py", line 976, in full_setup
    self._protein.reformat_protein()
  File "/vortexfs1/home/anmeyer/.local/lib/python3.8/site-packages/phd3/protein/protein.py", line 204, in reformat_protein
    self.relabel()
  File "/vortexfs1/home/anmeyer/.local/lib/python3.8/site-packages/phd3/protein/protein.py", line 298, in relabel
    self.make_bond_table()
  File "/vortexfs1/home/anmeyer/.local/lib/python3.8/site-packages/phd3/protein/protein.py", line 538, in make_bond_table
    raise OSError("mol2_file")
OSError: mol2_file
	If the issue persists, contact the developers
```

**Comment by jtfuller3** [comment]
Hi,

What version of open babel do you have?

**Comment by jtfuller3** [comment]
Sorry, the wiki says open babel 2.4.0 but we updated to 3.1.1.  I changed the wiki with a link to 3.1.1

**Comment by jtfuller3** [comment]
Actually we're changing it to work for both

**Comment by annaliesemeyer** [comment]
Great, thank you!

**Comment by annaliesemeyer** [comment]
This does not seem to have fixed the issue - with openbabel 3.1.1 I'm still getting the exact same error.

**Comment by jtfuller3** [comment]
The latest PHD3 version should work with either openbabel version.  You might need to add "export BABELDIR=/path/to/openbabel/bin/" to your .bashrc.  Can you call openbabel on the pdb file it makes before the error?

**Comment by annaliesemeyer** [comment]
Yes, I can. I did a clean install of the github repo and made a new environment, and now am getting
```
(phd3clean) [anmeyer@poseidon-l1 jsoninputs]$ setupphd.py 
Traceback (most recent call last):
  File "/vortexfs1/home/anmeyer/.conda/envs/phd3clean/bin/setupphd.py", line 5, in <module>
    from phd3.bin.setupphd import main
  File "/vortexfs1/home/anmeyer/.local/lib/python3.8/site-packages/phd3/__init__.py", line 1, in <module>
    from .controller import *
  File "/vortexfs1/home/anmeyer/.local/lib/python3.8/site-packages/phd3/controller.py", line 17, in <module>
    from . import iteration
  File "/vortexfs1/home/anmeyer/.local/lib/python3.8/site-packages/phd3/iteration.py", line 23, in <module>
    import hdbscan
  File "/vortexfs1/home/anmeyer/.local/lib/python3.8/site-packages/hdbscan/__init__.py", line 1, in <module>
    from .hdbscan_ import HDBSCAN, hdbscan
  File "/vortexfs1/home/anmeyer/.local/lib/python3.8/site-packages/hdbscan/hdbscan_.py", line 9, in <module>
    from sklearn.base import BaseEstimator, ClusterMixin
  File "/vortexfs1/home/anmeyer/.local/lib/python3.8/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/vortexfs1/home/anmeyer/.local/lib/python3.8/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/vortexfs1/home/anmeyer/.local/lib/python3.8/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/vortexfs1/home/anmeyer/.local/lib/python3.8/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/vortexfs1/home/anmeyer/.local/lib/python3.8/site-packages/scipy/stats/__init__.py", line 345, in <module>
    from .stats import *
  File "/vortexfs1/home/anmeyer/.local/lib/python3.8/site-packages/scipy/stats/stats.py", line 169, in <module>
    import scipy.special as special
  File "/vortexfs1/home/anmeyer/.local/lib/python3.8/site-packages/scipy/special/__init__.py", line 640, in <module>
    from ._ufuncs import *
ImportError: /vortexfs1/home/anmeyer/.local/lib/python3.8/site-packages/scipy/special/_ufuncs.cpython-38-x86_64-linux-gnu.so: undefined symbol: _gfortran_stop_numeric_f08

```
Thanks!

**Comment by annaliesemeyer** [comment]
This may be a scipy issue, not a phd3 issue, so if it's not something you have encountered before don't worry too much about it. Thanks!

**Comment by annaliesemeyer** [comment]
The mol2 issue I was getting seems to stem from the fact that protein.py isn't recognizing that it did create a bond.mol2 file which is residing in a new dmd_setup folder the program created. Not sure how to get past this, so any help would be appreciated!

**Comment by jtfuller3** [comment]
What's the current error and what are the contents of bond.mol2?

**Comment by annaliesemeyer** [comment]
I have two separate environments going - but it seems like the one that's working better is the mol2 error. The bond.mol2 file is below as a text file
[bond.mol2.txt](https://github.com/alexandrova-lab-ucla/phd3/files/7809605/bond.mol2.txt)

**Comment by jtfuller3** [comment]
What is the error message and did you update to the latest version?

**Comment by annaliesemeyer** [comment]
The error message is 
```
(phd3-3.8) [anmeyer@pn040 jsoninputs]$ ls
4rdt_loops.pdb  phdinput.json
(phd3-3.8) [anmeyer@pn040 jsoninputs]$ setupphd.py
	Could not create 4rdt_loops.pdb mol2 file!
	OSError encountered, likely an issue with moving files around
Traceback (most recent call last):
  File "/vortexfs1/home/anmeyer/.local/lib/python3.8/site-packages/phd3/bin/setupphd.py", line 24, in main
    sdj = setupPHDjob()
  File "/vortexfs1/home/anmeyer/.local/lib/python3.8/site-packages/phd3/setupjob.py", line 1338, in __init__
    sdj.full_setup()
  File "/vortexfs1/home/anmeyer/.local/lib/python3.8/site-packages/phd3/setupjob.py", line 976, in full_setup
    self._protein.reformat_protein()
  File "/vortexfs1/home/anmeyer/.local/lib/python3.8/site-packages/phd3/protein/protein.py", line 204, in reformat_protein
    self.relabel()
  File "/vortexfs1/home/anmeyer/.local/lib/python3.8/site-packages/phd3/protein/protein.py", line 298, in relabel
    self.make_bond_table()
  File "/vortexfs1/home/anmeyer/.local/lib/python3.8/site-packages/phd3/protein/protein.py", line 538, in make_bond_table
    raise OSError("mol2_file")
OSError: mol2_file
	If the issue persists, contact the developers
``` 
as above and I'm using the most up to date github repo and openbabel 3.1.1

**Comment by jtfuller3** [comment]
And it does create a mol2 file before giving this error?

**Comment by annaliesemeyer** [comment]
Yes
